/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContactInfo: typeof import('./src/components/ContactInfo.vue')['default']
    Education: typeof import('./src/components/Education.vue')['default']
    Experience: typeof import('./src/components/Experience.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Stack: typeof import('./src/components/Stack.vue')['default']
  }
}
